name: Build
on: [push, pull_request]

env:
  COVERAGE_REPORT_PATH: "target/site/jacoco/jacoco.xml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          files: "${{ env.REPORT_NAME }}"
          fail_ci_if_error: true
